### ISSUE TITLE
Question about the input for entity linking based retrieval system

### ISSUE THREAD

**Issue by hitercs** [anthonywchen/AmbER-Sets#4]
Hi,

Thanks for your nice work. 
I have a question about the input format for entity linking based retrieval system. 
Did you feed the mention boundary to the BLINK and Bootleg? or just original query which relies the entity linker to do both mention detection and entity disambiguation. As I know, BLINK and Bootleg are two entity disambiguation models. What mention detection components did you use during the experiments.

Thanks!

**Comment by anthonywchen** [comment]
Hi Shuang,

For BLINK, we used FLAIR to do mention detection as is done in the [official repository](https://github.com/facebookresearch/BLINK). For Bootleg, we used a simple dictionary based candidate lookup to do mention detection as is done in the [E2E Bootleg tutorial](https://render.githubusercontent.com/view/ipynb?color_mode=auto&commit=b179aa906e708626c4149e12f52c15c79328fcd8&enc_url=68747470733a2f2f7261772e67697468756275736572636f6e74656e742e636f6d2f48617a7952657365617263682f626f6f746c65672f623137396161393036653730383632366334313439653132663532633135633739333238666364382f7475746f7269616c732f656e6432656e645f6e65645f7475746f7269616c2e6970796e62&nwo=HazyResearch%2Fbootleg&path=tutorials%2Fend2end_ned_tutorial.ipynb&repository_id=286367631&repository_type=Repository#1.-Detect-Mentions). Hope this helps!
